export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const CHANGE_DEFFICLTY = "CHANGE_DEFFICLTY";
export const CHANGE_TYPE = "CHANGE_TYPE";
export const CHANGE_AMOUNT = "CHANGE_AMOUNT";
export const CHANGE_SCORE = "CHANGE_SCORE";
